simulation:
  step: 0.1
  timespan: 200

variables:
  p53:
    label: "p53"
    initial: 27000
  MDMc:
    label: "MDM2 cytoplazmatyczne"
    initial: 12000
  MDMn:
    label: "MDM2 jądrowe"
    initial: 155000
  PTEN:
    label: "PTEN"
    initial: 17000

parameters:
  p1: 8.8
  p2: 440
  p3: 100

  d1: 1.375e-14
  d2: 1.375e-4
  d3: 3e-5

  k1: 1.925e-4
  k2: 1e5
  k3: 1.5e5

equations:
  p53: "3600 * ({p1} - {d1} * p53 * MDMn**2)"

  MDMc: "3600 * ({p2} * p53**4 / (p53**4 + {k2}**4) - {k1} * ({k3}**2 / ({k3}**2 + PTEN**2)) * MDMc - {d2} * MDMc)"

  MDMn: "3600 * ({k1} * ({k3}**2 / ({k3}**2 + PTEN**2)) * MDMc - {d2} * MDMn)"

  PTEN: "3600 * ({p3} * p53**4 / (p53**4 + {k2}**4) - {d3} * PTEN)"

scenarios:
  A:
    description: "Brak uszkodzenia DNA, PTEN aktywny, brak siRNA"
    parameters:
      d2: 1.375e-5
      p2: 440
      p3: 100

  B:
    description: "Uszkodzenie DNA, PTEN aktywny, brak siRNA"
    parameters:
      d2: 1.375e-4
      p2: 440
      p3: 100

  C:
    description: "Nowotwór: PTEN wyłączony, uszkodzenie DNA, brak siRNA"
    parameters:
      d2: 1.375e-4
      p2: 440
      p3: 0
    initial:
      PTEN: 0

  D:
    description: "Terapia: PTEN wyłączony, uszkodzenie DNA, siRNA aktywne"
    parameters:
      d2: 1.375e-4
      p2: 8.8
      p3: 0
    initial:
      PTEN: 0